version: '3.9'

services:
  auth:
    build: ./services/auth
    container_name: mp_auth_service
    ports:
      - "4000:4000"
    env_file:
      - ./services/auth/.env
    restart: unless-stopped

  cases:
    build: ./services/cases
    container_name: mp_cases_service
    ports:
      - "4001:4001"
    env_file:
      - ./services/cases/.env
    restart: unless-stopped

  reports:
    build: ./services/reports
    container_name: mp_reports_service
    ports:
      - "4002:4002"
    env_file:
      - ./services/reports/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: mp_frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - auth
      - cases
      - reports
