apiVersion: v1
kind: ConfigMap
metadata:
  name: mp-cases-config
  namespace: mp-cases-platform
data:
  NODE_ENV: "production"
  DB_HOST: "your-database-host"
  DB_PORT: "5432"
  DB_NAME: "mp_cases_platform" 