apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mp-cases-platform

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- auth-deployment.yaml
- cases-deployment.yaml
- reports-deployment.yaml
- frontend-deployment.yaml
- services.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: mp-cases-platform
  app.kubernetes.io/version: v1.0 